import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';
import '../../i18n';
import React, { useEffect, useState } from 'react';
import { appWithTranslation } from 'next-i18next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Maintenance from './Maintenance';
import Script from 'next/script';


const GA_TRACKING_ID = 'G-YPYZMXV8BE';

const metadata = {
  title: 'Home wider accessibility',
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps }) {
  const { locale } = useRouter();
  const direction = locale === 'ar' || locale === 'he' ? 'rtl' : 'ltr';


  const isMaintenanceMode = true;
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null; // Evitar renderizar hasta que esté montado en el cliente
  }

  if (isMaintenanceMode) {
    return (
      <>
        <Head>
          <title>Próximamente - Wider</title>
          <meta name="description" content="Nuestro sitio está en construccion. Vuelve pronto." />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <Maintenance />
      </>
    );
  }

  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${GA_TRACKING_ID}');
        `}
      </Script>
      {/* Cookie banner script */}
      <Script
        strategy="afterInteractive"
        src="//cdn.cookie-script.com/s/162af65b7001774c2e1d8c845bb27a32.js"
        type="text/javascript"
        charset="UTF-8"
      />

      <div dir={direction}>
        <Header />
        <main>
          <Component {...pageProps} />
        </main>
        <Footer />
      </div>
    </>
  );
}

export default appWithTranslation(MyApp);
