import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';
import '../../i18n';
import React, { useEffect, useState } from 'react';
import { appWithTranslation, useTranslation } from 'next-i18next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Maintenance from './Maintenance';
import Script from 'next/script';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

const GA_TRACKING_ID = 'G-YPYZMXV8BE';

const metadata = {
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps }) {
  const { locale, pathname } = useRouter();
  const direction = locale === 'ar' || locale === 'he' ? 'rtl' : 'ltr';

  // Si la página es '/AccessibilityStatement', usa ese namespace
  const { t } = useTranslation(pathname.includes('/AccessibilityStatement') ? 'accessibilityStatement' : 'common');

  const isMaintenanceMode = false;
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null; // Evitar renderizar hasta que esté montado en el cliente
  }

  if (isMaintenanceMode) {
    return (
      <>
        <Head>
          <title>Próximamente - Wider</title>
          <meta name="description" content="Nuestro sitio está en construcción. Vuelve pronto." />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <Maintenance />
      </>
    );
  }

  // Definir el título según la ruta y el namespace adecuado
  let pageTitle = t('titleHome'); // Título por defecto
  if (pathname.includes('/AccessibilityStatement')) {
    pageTitle = t('titleAccessibilityStatement', { ns: 'accessibilityStatement' });
  } else if (pathname.includes('/PrivacyPolicy')) {
    pageTitle = t('titlePrivacyPolicy', { ns: 'privacyPolicy' });
  }

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${GA_TRACKING_ID}');
        `}
      </Script>
      <Script
        strategy="afterInteractive"
        src="//cdn.cookie-script.com/s/162af65b7001774c2e1d8c845bb27a32.js"
        type="text/javascript"
        charset="UTF-8"
      />

      <div dir={direction}>
        <Header />
        <main>
          <Component {...pageProps} />
        </main>
        <Footer />
      </div>
    </>
  );
}

// Cargar los namespaces correctos en cada página
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'accessibilityStatement', 'privacyPolicy'])),
  },
});

export default appWithTranslation(MyApp);
