import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';
import '../../i18n'; // Importar la inicialización de i18next
import React, { useEffect, useState } from 'react';
import { appWithTranslation } from 'next-i18next';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Maintenance from './Maintenance'; // Modo mantenimiento (por si es necesario)
import { GoogleAnalytics } from 'nextjs-google-analytics'; // Importa Google Analytics

const metadata = {
  title: 'Home wider accessibility',
  description: 'Generated by create next app',
};

function MyApp({ Component, pageProps }) {
  const { locale } = useRouter();
  const direction = locale === 'ar' || locale === 'he' ? 'rtl' : 'ltr'; // Manejo de texto RTL para árabe o hebreo

  const GA_TRACKING_ID = 'G-YPYZMXV8BE';

  const isMaintenanceMode = false;
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null; // Evitar renderizar hasta que esté montado en el cliente
  }

  if (isMaintenanceMode) {
    return (
      <>
        <Head>
          <title>Próximamente - Wider</title>
          <meta name="description" content="Nuestro sitio está en construccion. Vuelve pronto." />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <Maintenance />
      </>
    );
  }

  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      {/* Componente GoogleAnalytics */}
      <GoogleAnalytics trackPageViews id={GA_TRACKING_ID} />

      <div dir={direction}>
        <Header />
        <main>
          <Component {...pageProps} />
        </main>
        <Footer />
      </div>
    </>
  );
}

export default appWithTranslation(MyApp);
