import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Content from "@/components/Content";
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home wider accessibility",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Header />
        <Content />
        <Footer />
      </body>
    </html>
  );
}
